---
include:
  - remote: https://gitlab.com/platform-engineering-org/gitlab-ci/-/raw/main/templates/pre-commit.gitlab-ci.yml # yamllint disable-line rule:line-length

stages:
  - pre-commit

pre-commit:
  variables:
    SKIP: terraform_validate
  extends: .pre-commit

terraform-validate:
  image:
    name: hashicorp/terraform:1.8.3@sha256:56234a3337d81a28595a4b08abc14db9da91a5ac1596817cbec0d681f2fc5374
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - apk --no-cache add py3-pip openssh-client git bash
    - pip3 install --break-system-packages pre-commit
  script:
    - pre-commit run -a terraform_validate
  needs: []
  stage: pre-commit
